version: "3"

services:
  k1:
    image: wurstmeister/kafka:2.12-2.1.0
    hostname: k1
    networks:
      - core-overlay
    volumes:
      - kfk-data:/kafka
    ports:
      - 17812:17812
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=192.168.100.220:2171,192.168.100.189:2171,192.168.100.140:2171
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ADVERTISED_LISTENERS=INT://:17810,EXT://192.168.100.220:17812
      - KAFKA_INTER_BROKER_LISTENER_NAME=INT
      - KAFKA_BROKER_ID=0
      - KAFKA_CLEANUP_POLICY=compact
      - KAFKA_LISTENERS=INT://:17810,EXT://:17812
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,INT:PLAINTEXT,EXT:PLAINTEXT
      - KAFKA_PORT=17810
    deploy:
      placement:
        constraints: [node.labels.kfknode == 0]
  k2:
    image: wurstmeister/kafka:2.12-2.1.0
    hostname: k2
    networks:
      - core-overlay
    volumes:
      - kfk-data:/kafka
    ports:
      - 17813:17812
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=192.168.100.220:2171,192.168.100.189:2171,192.168.100.140:2171
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ADVERTISED_LISTENERS=INT://:17810,EXT://192.169.100.35:17813
      - KAFKA_INTER_BROKER_LISTENER_NAME=INT
      - KAFKA_BROKER_ID=1
      - KAFKA_CLEANUP_POLICY=compact
      - KAFKA_LISTENERS=INT://:17810,EXT://:17812
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,INT:PLAINTEXT,EXT:PLAINTEXT
      - KAFKA_PORT=17810
    deploy:
      placement:
        constraints: [node.labels.kfknode == 1]
  k3:
    image: wurstmeister/kafka:2.12-2.1.0
    hostname: k3
    networks:
      - core-overlay
    volumes:
      - kfk-data:/kafka
    ports:
      - 17814:17812
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=192.168.100.220:2171,192.168.100.189:2171,192.168.100.140:2171
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ADVERTISED_LISTENERS=INT://:17810,EXT://192.168.100.94:17814
      - KAFKA_INTER_BROKER_LISTENER_NAME=INT
      - KAFKA_BROKER_ID=3
      - KAFKA_CLEANUP_POLICY=compact
      - KAFKA_LISTENERS=INT://:17810,EXT://:17812
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,INT:PLAINTEXT,EXT:PLAINTEXT
      - KAFKA_PORT=17810
    deploy:
      placement:
        constraints: [node.labels.kfknode == 2]

networks:
  core-overlay:
    external: true

volumes:
  kfk-data:
  zk-data:
  zk-datalog:
  zk-logs:
#  zk-conf:
