version: "3.4"
services:
  cassandra:
    image: docker.io/cassandra:3.11
    hostname: cassandra
    ports:
      - 17000:7000 # message service, storage_port
      - 17001:9042 # CQL client
      - 17002:9160 # thrift service
    volumes:
      - /tmp:/tmp
      - cassandra-data:/var/lib/cassandra
    environment:
      - CASSANDRA_DC=localhost
      - CASSANDRA_START_RPC=true
      - CASSANDRA_LISTEN_ADDRESS=localhost
      - CASSANDRA_BROADCAST_ADDRESS=localhost
      - CASSANDRA_SEEDS=localhost
    deploy:
      placement:
        constraints: [node.labels.zknode == 1]

volumes:
  cassandra-data:
