[package]
name = "zoo"
version = "0.1.0"
authors = ["Zex Li <dbloodwxp@gmail.com>"]

[dependencies]
rand = "0.5.0"

[[bin]]
name = "qsort"
path = "algo_rust/qsort.rs"

[[bin]]
name = "mt"
path = "algo_rust/mt.rs"

[[bin]]
name = "msort"
path = "algo_rust/msort.rs"
