[package]
name = "trust"
version = "0.1.0"
authors = ["Zex Li <dbloodwxp@gmail.com>"]

[dependencies]
rand = "0.5.0"
postgres = "0.15.2"
#log4rs = "0.8.0"
http = "0.1.5"

[[bin]]
name = "trust_backend"
path = "apps/trust_backend.rs"
