version: "3.4"

services:
  grafana:
    image: grafana/grafana:5.2.0
    networks:
      - tele-net
    hostname: '{{.Node.Hostname}}'
    ports:
      - protocol: tcp
        published: 13000
        target: 3000
        mode: host
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-cfg:/etc/grafana
    deploy:
      placement:
        constraints: [node.hostname == core.master]
  influxdb:
    image: docker.io/influxdb:alpine
    hostname: influxdb
    networks:
      - tele-net
    ports:
      - protocol: tcp
        published: 13001
        target: 8086
        mode: host
    volumes:
      - influxdb-data:/var/lib/influxdb
    deploy:
      placement:
        constraints: [node.hostname == core.master]
  telegraf:
    image: telegraf:alpine
    hostname: '{{.Node.Hostname}}'
    network_mode: host
    networks:
      - tele-net
    environment:
      - HOST_PROC=/host/proc
    depends_on:
      - influxdb
    volumes:
      - telegraf-data:/var/lib/telegraf
      - /telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /proc:/host/proc
      - /var/run/utmp:/var/run/utmp
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    ports:
      - protocol: udp
        published: 13002
        target: 8092
        mode: host
      - protocol: tcp
        published: 13003
        target: 8094
        mode: host
      - protocol: udp
        published: 13004
        target: 8125
        mode: host
    deploy:
      placement:
        constraints: [node.hostname == core.master]
  telegraf_global:
    image: telegraf:alpine
    hostname: '{{.Node.Hostname}}'
    network_mode: host
    networks:
      - tele-net
    environment:
      - HOST_PROC=/host/proc
    volumes:
      - telegraf-data:/var/lib/telegraf
      - /telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
      - /proc:/host/proc
      - /var/run/utmp:/var/run/utmp
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    ports:
      - protocol: udp
        published: 13002
        target: 8092
        mode: host
      - protocol: tcp
        published: 13003
        target: 8094
        mode: host
      - protocol: udp
        published: 13004
        target: 8125
        mode: host
    deploy:
      placement:
        constraints: [node.hostname != core.master]
      mode: global

networks:
  tele-net:

volumes:
  telegraf-data:
  influxdb-data:
  grafana-data:
  grafana-cfg:
