version: "3.4"

services:
  spark1:
    image: zlynch/spark:2.4.0
    hostname: spark1
    networks:
      - zk-net
    ports:
      - published: 18880
        target: 8080
        mode: host
      - published: 18877
        target: 7077
        mode: host
    environment:
      SPARK_NO_DAEMONIZE: 1
    command: /opt/spark-2.4.0-bin-hadoop2.7/sbin/start-master.sh
    deploy:
      placement:
        constraints: [node.labels.zknode == 1]
  spark2:
    image: zlynch/spark:2.4.0
    hostname: spark2
    networks:
      - zk-net
    ports:
      - published: 18880
        target: 8081
        mode: host
    environment:
      SPARK_NO_DAEMONIZE: 1
    command: /opt/spark-2.4.0-bin-hadoop2.7/sbin/start-slave.sh spark://spark1:7077
    deploy:
      placement:
        constraints: [node.labels.zknode == 2]
  spark3:
    image: zlynch/spark:2.4.0
    hostname: spark3
    networks:
      - zk-net
    ports:
      - published: 18880
        target: 8081
        mode: host
    environment:
      SPARK_NO_DAEMONIZE: 1
    command: /opt/spark-2.4.0-bin-hadoop2.7/sbin/start-slave.sh spark://spark1:7077
    deploy:
      placement:
        constraints: [node.labels.zknode == 3]

networks:
  zk-net:
    external: true
