version: "3.4"

services:
  profile:
    image: zlynch/profile:1.0
    hostname: profile
    networks:
      - zk-net
#    ports:
#      - published: 18880
#        target: 8080
#        mode: host
    environment:
      PYTHONPATH: /opt/woody
      CASSANDRA_SERVERS: 192.168.70.220,192.168.70.189,192.168.70.35
      CASSANDRA_PORT: 17001
      CASSANDRA_USER: dev
      CASSANDRA_PASS: dcb5c69fedb78e9a29a3
      KAFKA_BROKERS: 192.168.70.220:17812,192.168.70.35:17812,192.168.70.94:17812
      SPARK_HOME: /opt/spark-2.4.0-bin-hadoop2.7
      SPARK_MASTER: spark://spark1:7077
    command: /opt/spark/bin/spark-submit --master spark://spark1:7077 --jars /opt/spark-extern/spark-streaming-kafka-0-8-assembly_2.11-2.4.0.jar woody/apps/profile_aggr.py
  producer:
    image: zlynch/producer:1.0
    hostname: producer
    networks:
      - zk-net
    # outside cluster: 192.168.70.220:17812,192.168.70.35:17812,192.168.70.94:17812
    command: build/producer -brokers k1:17812,k2:17812,k3:17812 -alsologtostderr
    deploy:
      placement:
        constraints: [node.hostname != core.master]
      replicas: 0

networks:
  zk-net:
    external:
      name: kfk_zk-net
