apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-data
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: slow
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-data
  labels:
    type: local
spec:
  storageClassName: slow
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/spark-data"
